name: Tic-Tac-Toe Game

on:
  issue_comment:
    types: [created]

jobs:
  play-tictactoe:
    if: github.event.issue.title == 'Tic-Tac-Toe Game'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Tic-Tac-Toe Logic
        run: python .github/scripts/tictactoe.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
